title: Race Element
url: https://race.elementfuture.com
author: RiddleTime

description: > # this means to ignore newlines until "show_exerpts:"
  Provides Solutions for Sim Racing<br/>
  <img src="https://hits.seeyoufarm.com/api/count/keep/badge.svg?url=https%3A%2F%2Fgithub.com%2FRiddleTime%2FRace-Element&amp;count_bg=%23FF4500&amp;title_bg=%23555555&amp;icon=&amp;icon_color=%23E7E7E7&amp;title=Usage%3A+Today+%2F+All-time&amp;edge_flat=false"><br/>
  <a href="https://race.elementfuture.com/2023/01/12/get-started.html">Download</a>
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://paypal.me/CompetizioneManager
      icon: heart
      color: red
    - url: https://discord.gg/26AAEW5mUq 
      icon: discord
      color: purple
    - url: https://github.com/RiddleTime/Race-Element
      icon: github
      color: white
    - url: https://github.com/RiddleTime/Race-Element/releases/latest
      icon: arrow-alt-circle-down
      color: orange  
      
  avatar_source: local
  avatar_path: /other resources/race element icon 2.png

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
