title: Race Element
url: https://race.elementfuture.com
author: RiddleTime

description: > # this means to ignore newlines until "show_exerpts:"
  Provides tooling for Sim Racing
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://discord.gg/26AAEW5mUq 
      icon: discord
      color: purple
    - url: https://github.com/RiddleTime/Race-Element
      icon: github-square
      color: white
    - url: https://github.com/RiddleTime/Race-Element/releases/latest
      icon: arrow-down
      color: white
    
      
  avatar_source: local
  avatar_path: /other resources/race element icon.png

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
