version: 0.1.{build}.{branch}
branches:
  only:
    - dev
    - release
    - csharp12
  except:
    - gh-pages
    - pages
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: nuget restore
build_script:
- cmd: dotnet publish -p:PublishProfile=FolderProfile
test: off
artifacts:
- path: '**\RaceElement.exe'
  name: Race Element
deploy:
- provider: Webhook
  on:
    branch: release
  url: https://app.signpath.io/API/v1/9bd5dbe6-3047-4e42-9dbb-0bf694ed7e48/Integrations/AppVeyor?ProjectKey=Race-Element&SigningPolicyKey=release-signing
  authorization:
    secure: H+at4ZC2qvHHDcdgGw+882oDYFv3G7zChPU97QGl5l0WCSoUgCtW34OG7Ky0x1cQ7HWdVJJGP5cHl6+j6z7Z5A==
