version: 0.1.{build}.{branch}
branches:
  only:
  - release
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Race Element.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: '**\bin\Release\RaceElement.exe'
  name: Race Element
deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/9bd5dbe6-3047-4e42-9dbb-0bf694ed7e48/Integrations/AppVeyor?ProjectKey=Race-Element&SigningPolicyKey=test-signing
  authorization:
    secure: H+at4ZC2qvHHDcdgGw+882oDYFv3G7zChPU97QGl5l0WCSoUgCtW34OG7Ky0x1cQ7HWdVJJGP5cHl6+j6z7Z5A==
