version: 1.0.{build}.{branch}
branches:
  only:
  - dev
  - release
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Race Element.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: '**\bin\Release\RaceElement.exe'
  name: Race Element Beta
deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/9bd5dbe6-3047-4e42-9dbb-0bf694ed7e48/Integrations/AppVeyor?ProjectSlug=Race-Element&SigningPolicySlug=release-signing&ArtifactConfigurationSlug=Race_Element_Release
  authorization:
    secure: H+at4ZC2qvHHDcdgGw+882oDYFv3G7zChPU97QGl5l0WCSoUgCtW34OG7Ky0x1cQ7HWdVJJGP5cHl6+j6z7Z5A==
